window.onload = function () {
                                        
                                        var chart = new CanvasJS.Chart("chartContainer", {
                                            zoomEnabled: true,
                                            backgroundColor: "transparent",
                                            animationEnabled: true,
                                            title:{
                                                text: "",
                                               
                                            },
                                            axisX: {
                                                title:"Orders"
                                            },
                                            axisY: {
                                                title:"Sells"
                                            },
                                            legend:{
                                                horizontalAlign: "center"
                                            },
                                            data: [{
                                                type: "bubble",
                                                backgroundcolor: "red",  
                                                showInLegend: true,
                                                legendText: "Size of Bubble Represents Avg Sells",
                                                legendMarkerType: "circle",
                                                legendMarkerColor: "grey",
                                                toolTipContent: "<b>{name}</b><br/>Orders: {x} <br/> Sells: {y}<br/> Avg Sells: {z}k MX",
                                                dataPoints: [
                                                { x:1.4, y:1920.4, z:1.3, name: 'PUERTA TLATELOLCO' },
                                        { x:1.8, y:3059.3, z:1.7, name: 'PLAYA DEL CARMEN' },
                                        { x:0.4, y:542.9, z:1.3, name: 'MONCLOVA' },
                                        { x:1.7, y:2551.1, z:1.5, name: 'IRAPUATO' },
                                        { x:2.5, y:3618.6, z:1.5, name: 'MERIDA NORTE' },
                                        { x:2.7, y:3742.8, z:1.4, name: 'LOPEZ MATEOS' },
                                        { x:1, y:1339, z:1.3, name: 'SENDERO' },
                                        { x:2.2, y:3065.5, z:1.4, name: 'LOMAS VERDES' },
                                        { x:1.9, y:2677.2, z:1.4, name: 'DOMINGO DIEZ' },
                                        { x:2.9, y:5861.8, z:2, name: 'COLIMA NORTE' },
                                        { x:2.1, y:4494.4, z:2.1, name: 'ACAPULCO DIAMANTE' },
                                        { x:3.6, y:5501.9, z:1.5, name: 'BARRANCA DEL MUERTO' },
                                        { x:1.5, y:1904.1, z:1.2, name: 'IXTAPALUCA' },
                                        { x:1, y:1110.4, z:1.1, name: 'ALTOZANO' },
                                        { x:1.7, y:2763.1, z:1.6, name: 'BELISARIO DOMINGUEZ' },
                                        { x:1.3, y:1584.3, z:1.2, name: 'LA HUASTECA' },
                                        { x:0.7, y:806.7, z:1.1, name: 'PLAZA SAN PEDRO' },
                                        { x:1.7, y:2088, z:1.2, name: 'GALERIAS LAS TORRES' },
                                        { x:2.9, y:3491.2, z:1.2, name: 'SUPER PLAZA ECATEPEC' },
                                        { x:0.7, y:1502.2, z:2.2, name: 'CHAPALA' },
                                        { x:0.9, y:1334.3, z:1.5, name: 'GALERIAS SALTILLO' },
                                        { x:1.4, y:1724.6, z:1.3, name: 'SANTA ELENA' },
                                        { x:1.1, y:1836.6, z:1.7, name: 'BAHIA DE BANDERAS' },
                                        { x:2.3, y:3653.9, z:1.6, name: 'CUEMANCO' },
                                        { x:1.6, y:2816.3, z:1.7, name: 'LERMA TOLUCA' },
                                        { x:1.1, y:2032.5, z:1.8, name: 'HIPERPLAZA TEXCOCO' },
                                        { x:1.3, y:2225.5, z:1.7, name: 'TERCER MILENIO (ANILLO)' },
                                        { x:3.5, y:4540.1, z:1.3, name: 'PORTAL CENTRO' },
                                        { x:1.6, y:2106.8, z:1.3, name: 'EL ROSARIO' },
                                        { x:1.6, y:2755.4, z:1.7, name: 'ESPACIO ESMERALDA' },
                                        { x:1, y:1496.4, z:1.5, name: 'PLAYAS DE TIJUANA' },
                                        { x:1.6, y:2523.1, z:1.5, name: 'LA ANTORCHA' },
                                        { x:1.6, y:2799.8, z:1.7, name: 'GOMEZ MORIN' },
                                        { x:1.4, y:2013.8, z:1.4, name: 'CLUB DE GOLF' },
                                        { x:5.9, y:11379.4, z:1.9, name: 'PATIO SANTA FE' },
                                        { x:1.5, y:2267.7, z:1.5, name: 'CIUDAD JUDICIAL' },
                                        { x:0.9, y:1131.3, z:1.3, name: 'MACRO PLAZA OAXACA' },
                                        { x:1.4, y:2077.4, z:1.5, name: 'LA PASTORA' },
                                        { x:4.4, y:5996.2, z:1.4, name: 'PLAZA ORIENTE' },
                                        { x:1.9, y:2718.4, z:1.4, name: 'LAS TORRES' },
                                        { x:1.8, y:2325.8, z:1.3, name: 'VALLE ORIENTE' },
                                        { x:2.1, y:2964.8, z:1.4, name: 'BLVD COLOSIO' },
                                        { x:1.2, y:1650.5, z:1.4, name: 'CARRETERA 57' },
                                        { x:2.1, y:2903.4, z:1.4, name: 'MIGUEL ALEMAN' },
                                        { x:2.1, y:2529.7, z:1.2, name: 'CD. JARDIN' },
                                        { x:1.5, y:2241.9, z:1.5, name: 'ANGELOPOLIS' },
                                        { x:1.8, y:2276.3, z:1.3, name: 'SAN NICOLAS' },
                                        { x:1.3, y:1438.8, z:1.1, name: 'MAHATMA GANDHI' },
                                        { x:1.8, y:2642.3, z:1.4, name: 'COFRADIAS' },
                                        { x:2.5, y:3702.2, z:1.5, name: 'VALLARTA' },
                                        { x:6, y:9824.7, z:1.6, name: 'LOMAS' },
                                        { x:3.3, y:4418.8, z:1.4, name: 'TEPEYAC' },
                                        { x:1.4, y:1872.8, z:1.3, name: 'AGUASCALIENTES' },
                                        { x:3.2, y:4308.2, z:1.4, name: 'TLAHUAC' },
                                        { x:2.7, y:4944.4, z:1.8, name: 'ACAPULCO' },
                                        { x:2.1, y:2469.3, z:1.2, name: 'QUERETARO' },
                                        { x:0.5, y:434.2, z:0.9, name: 'JARDINES DEL COUNTRY' },
                                        { x:1.4, y:1547.8, z:1.1, name: 'TORREON' },
                                        { x:1.2, y:1530.5, z:1.3, name: 'CIUDAD JUAREZ' },
                                        { x:1.5, y:2145.2, z:1.4, name: 'TAMPICO' },
                                        { x:3.4, y:5046.3, z:1.5, name: 'CULIACAN' },
                                        { x:2.9, y:5506.6, z:1.9, name: 'CD OBREGON' },
                                        { x:1.5, y:1482.7, z:1, name: 'MORELIA' },
                                        { x:6, y:12458.1, z:2.1, name: 'INTERLOMAS' },
                                        { x:3, y:4008.3, z:1.4, name: 'LABNA CANCUN I' },
                                        { x:2.7, y:3643.4, z:1.4, name: 'SAN LUIS POTOSI' },
                                        { x:1, y:1126.8, z:1.1, name: 'DURANGO' },
                                        { x:1.2, y:1608.4, z:1.3, name: 'TORRES LANDA' },
                                        { x:1.5, y:2197, z:1.5, name: 'AVERANDA' },
                                        { x:1.1, y:1546.1, z:1.4, name: 'PUNTA DEL ESTE' },
                                        { x:2.5, y:5341.6, z:2.2, name: 'VERACRUZ' },
                                        { x:4.3, y:6737.6, z:1.6, name: 'MIRAMONTES' },
                                        { x:3.2, y:4621.7, z:1.4, name: 'CUITLAHUAC' },
                                        { x:2.4, y:3562.4, z:1.5, name: 'PATIO TLALPAN' },
                                        { x:1.4, y:1360, z:1, name: 'PLAZA EL PASEO' },
                                        { x:5.7, y:7828.6, z:1.4, name: 'TLALPAN' },
                                        { x:1.6, y:2115.5, z:1.4, name: 'LA FE' },
                                        { x:4.6, y:7046.8, z:1.5, name: 'FELIX CUEVAS' },
                                        { x:1.3, y:1565.2, z:1.2, name: 'PONIENTE' },
                                        { x:0.6, y:1379.7, z:2.4, name: 'PLAZA ANA' },
                                        { x:2.3, y:3793.1, z:1.6, name: 'LA CRUZ' },
                                        { x:0.9, y:1556.2, z:1.7, name: 'SAN JOSE DEL CABO' },
                                        { x:1.2, y:1857.8, z:1.5, name: 'XALAPA SUR' },
                                        { x:2.1, y:3106.4, z:1.5, name: 'VALLE REAL' },
                                        { x:0.4, y:474, z:1.2, name: 'ENSENADA' },
                                        { x:1.2, y:1523.2, z:1.3, name: 'BLVD. MORELOS' },
                                        { x:1.7, y:2703.3, z:1.6, name: 'IRRIGACION' },
                                        { x:2.5, y:3895.2, z:1.6, name: 'PACHUCA' },
                                        { x:1.4, y:2223, z:1.6, name: 'LOS CABOS' },
                                        { x:1.8, y:2423.4, z:1.4, name: 'CUMBRES' },
                                        { x:2.2, y:2591.8, z:1.2, name: 'OJO DE AGUA TECAMAC' },
                                        { x:0.9, y:1363.7, z:1.5, name: 'PASEO REAL' },
                                        { x:1.2, y:1365.8, z:1.1, name: 'PLAZA VALLE' },
                                        { x:1.7, y:2802, z:1.6, name: 'PILARES' },
                                        { x:1.6, y:2376, z:1.4, name: 'BOULEVARD RUIZ CORTINEZ' },
                                        { x:1.1, y:1881.9, z:1.8, name: 'LAZARO CARDENAS' },
                                        { x:4.4, y:9743.6, z:2.2, name: 'AV JESUS DEL MONTE' },
                                        { x:1.7, y:2468, z:1.4, name: 'POLIGONO SUR' },
                                        { x:2.5, y:3393.1, z:1.4, name: 'PORTAL TLALNEPANTLA' },
                                        { x:0.5, y:593.3, z:1.2, name: 'Parque Guadiana' },
                                        { x:2, y:2721.3, z:1.4, name: 'MIL CUMBRES' },
                                        { x:1.8, y:2775.3, z:1.6, name: '5 DE FEBRERO NORTE' },
                                        { x:1.8, y:2438, z:1.4, name: 'PARAISO CUERNAVACA' },
                                        { x:0.5, y:637.8, z:1.2, name: 'LAS ADELITAS' },
                                        { x:2.4, y:2523.9, z:1, name: 'TONALA' },
                                        { x:0.9, y:1291.9, z:1.4, name: 'EJERCITO MEXICANO' },
                                        { x:3.5, y:4556.9, z:1.3, name: 'AVILA CAMACHO' },
                                        { x:1.3, y:1888, z:1.5, name: 'PITILLAL' },
                                        { x:2.5, y:3511.5, z:1.4, name: 'METEPEC' },
                                        { x:7.1, y:10561.5, z:1.5, name: 'UNIVERSIDAD' },
                                        { x:8, y:12097.5, z:1.5, name: 'BUENAVISTA' },
                                        { x:3.6, y:5824.9, z:1.6, name: 'SATELITE' },
                                        { x:4, y:6556.8, z:1.6, name: 'TAXQUENA' },
                                        { x:3.1, y:4285.4, z:1.4, name: 'ECHEGARAY' },
                                        { x:4.4, y:5545.7, z:1.3, name: 'AEROPUERTO' },
                                        { x:5.9, y:8584.4, z:1.5, name: 'PLATEROS' },
                                        { x:2.5, y:3273.3, z:1.3, name: 'SAN MANUEL' },
                                        { x:2.7, y:3842.4, z:1.4, name: 'PIRULES' },
                                        { x:3, y:4320.2, z:1.5, name: 'VILLA COAPA' },
                                        { x:2.2, y:3884, z:1.8, name: 'CUAJIMALPA' },
                                        { x:3.9, y:6035.7, z:1.6, name: 'REVOLUCION' },
                                        { x:3.6, y:4888, z:1.3, name: 'AZCAPOTZALCO' },
                                        { x:5.3, y:8769.6, z:1.7, name: 'PERIFERICO SUR' },
                                        { x:2.1, y:3059.9, z:1.4, name: 'REFORMA' },
                                        { x:2.2, y:2996.3, z:1.3, name: 'BALBUENA' },
                                        { x:2.4, y:4442.3, z:1.8, name: 'LAS AGUILAS' },
                                        { x:2.6, y:3481.1, z:1.4, name: 'TORRES DE LINDA VISTA' },
                                        { x:3.2, y:4688.2, z:1.5, name: 'NINO OBRERO' },
                                        { x:2, y:2790.9, z:1.4, name: 'LAS ANIMAS' },
                                        { x:1, y:1306.6, z:1.3, name: 'TEPIC' },
                                        { x:1.1, y:1859.1, z:1.7, name: 'CORDOBA' },
                                        { x:0.9, y:1336.3, z:1.5, name: 'AVENIDA CENTRAL' },
                                        { x:1.7, y:2409.3, z:1.4, name: 'TIJUANA HIPODROMO' },
                                        { x:2.4, y:2970.6, z:1.3, name: 'JARDINES DEL SOL' },
                                        { x:1.9, y:2479.9, z:1.3, name: 'SANTA MARIA COACALCO' },
                                        { x:0.5, y:556.5, z:1.1, name: 'GALERIAS DEL VALLE (PROGRESO)' },
                                        { x:0.6, y:1241.9, z:2.1, name: 'GUAYMAS' },
                                        { x:1.7, y:1944.1, z:1.2, name: 'MERIDA PENSIONES' },
                                        { x:0.8, y:1444.4, z:1.9, name: 'MANZANILLO' },
                                        { x:2, y:3123.7, z:1.6, name: 'PATRIA' },
                                        { x:1.5, y:2003, z:1.4, name: 'POLIGONO' },
                                        { x:0.7, y:832.5, z:1.1, name: 'CAMPECHE' },
                                        { x:1.9, y:2608.3, z:1.4, name: 'PERINORTE' },
                                        { x:1.1, y:2072.4, z:1.9, name: 'TIJUANA 2000' },
                                        { x:0, y:5.2, z:0.9, name: 'COLA DE BALLENA' },
                                        { x:2.8, y:3774.6, z:1.3, name: 'PERIFERICO CUAUTITLAN' },
                                        { x:0.2, y:343.8, z:1.4, name: 'ROSARITO' },
                                        { x:1.6, y:2013.4, z:1.3, name: 'Lago de Guadalupe' },
                                        { x:1.5, y:2359.8, z:1.5, name: 'ZACATECAS' },
                                        { x:3.7, y:4925.4, z:1.3, name: 'EDUARDO MOLINA' },
                                        { x:0.7, y:1465.6, z:2.1, name: 'LOS MOCHIS' },
                                        { x:0.5, y:665.8, z:1.2, name: 'Tlaxcala Estadio' },
                                        { x:2, y:2744.4, z:1.4, name: 'LAS ANTENAS' },
                                        { x:0.2, y:409.4, z:1.8, name: 'SAN CRISTOBAL' },
                                        { x:1.1, y:1497.4, z:1.3, name: 'RIO DE LOS REMEDIOS' },
                                        { x:0.9, y:1395.6, z:1.5, name: 'SANTIN' },
                                        { x:3.3, y:4334.6, z:1.3, name: 'PLAZA DE TOROS' },
                                        { x:1.6, y:2231.4, z:1.4, name: 'LAS AMERICAS'},
                                        { x:9, y:0, z:1, name: 'LAS AMERICAS'},
                                        
                                                ]
                                            }]
                                        });
                                        chart.render();
                                                                              
                                        }